#!/bin/sh

set -e

if [ -d /run/systemd/system ]; then
  if systemctl is-active sdr-server; then
    systemctl stop sdr-server.service
  fi
  if systemctl is-enabled sdr-server; then
    systemctl disable sdr-server.service
  fi
fi